# Generated by Django 5.1.4 on 2025-01-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogsetting',
            name='parameter_key',
        ),
        migrations.RemoveField(
            model_name='blogsetting',
            name='parameter_value',
        ),
        migrations.AddField(
            model_name='blogsetting',
            name='parameters',
            field=models.JSONField(default=list),
        ),
    ]
