# Generated by Django 5.1.4 on 2025-01-10 10:08

import uuid
from django.db import migrations, models


def backfill_uuid(apps, schema_editor):
    WordPress = apps.get_model('api', 'WordPress')
    for instance in WordPress.objects.filter(uuid__isnull=True):
        instance.uuid = uuid.uuid4()
        instance.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_blogsetting_parameter_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordpress',
            name='uuid',
            field=models.UUIDField(default=None, editable=False, unique=True),
        ),
        migrations.RunPython(backfill_uuid),
    ]
