# Generated by Django 5.1.4 on 2025-01-10 10:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_wordpress_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordpress',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
