# Generated by Django 5.1.4 on 2025-01-10 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_wordpress_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wordpress',
            old_name='uuid',
            new_name='wordpress_uuid',
        ),
    ]
