# Generated by Django 5.1.4 on 2025-01-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_uuid_wordpress_wordpress_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='wordpress_key',
            field=models.IntegerField(default=0),
        ),
    ]
