# Generated by Django 5.1.4 on 2025-01-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_blog_wordpress_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordpress',
            name='wordpress_key_name',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
