# Generated by Django 5.1.4 on 2025-01-17 12:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_wordpress_wordpress_key_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordpress',
            name='wordpress_key_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wordpress',
            name='wordpress_uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
