# Generated by Django 5.1.4 on 2025-01-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_user_subscription_id_user_subscription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='currency',
            field=models.CharField(default='usd', max_length=10),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='price_id',
            field=models.CharField(default='price_1QjegtDGI8UBmGXSauFynbuh', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
