# Generated by Django 5.1.4 on 2025-01-23 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_subscriptionplan_currency_subscriptionplan_price_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='plan_id',
        ),
    ]
