# Generated by Django 5.1.4 on 2025-01-23 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_plan_id_payment_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='stripe_payment_id',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.DeleteModel(
            name='PaymentHistory',
        ),
    ]
