# Generated by Django 5.1.4 on 2025-01-24 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_payment_stripe_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SuperAdmin', 'Super Administrator'), ('Admin', 'Administrator'), ('User', 'Regular User')], default='User', max_length=50),
        ),
    ]
