# Generated by Django 5.1.4 on 2025-01-30 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_userparameter_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userparameter',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to=settings.AUTH_USER_MODEL),
        ),
    ]
