# Generated by Django 5.1.4 on 2025-02-03 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_userparameter_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='payment',
            table=None,
        ),
    ]
