# Generated by Django 5.1.4 on 2025-02-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_payment_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='product_id',
            field=models.CharField(default='product id', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
