# Generated by Django 5.1.4 on 2025-02-26 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_blogsetting_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogsetting',
            name='parameters',
        ),
    ]
