# Generated by Django 5.1.4 on 2025-04-02 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_category_remove_userparameter_categories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGeneratedTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_generated_topics', to='api.category')),
                ('subcategories', models.ManyToManyField(blank=True, related_name='user_generated_topics', to='api.subcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_topics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
