# Generated by Django 5.1.4 on 2025-04-11 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergeneratedtopic',
            name='category',
        ),
        migrations.RemoveField(
            model_name='usergeneratedtopic',
            name='subcategories',
        ),
    ]
