# Generated by Django 5.1.4 on 2025-05-30 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_remove_usergeneratedtopic_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomBlogTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('usage_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_blog_topics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custom Blog Topic',
                'verbose_name_plural': 'Custom Blog Topics',
                'ordering': ['-usage_date'],
            },
        ),
    ]
