# Generated by Django 5.1.4 on 2025-06-03 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_customblogtopic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customblogtopic',
            name='description',
        ),
        migrations.AddField(
            model_name='customblogtopic',
            name='primary_keyword',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customblogtopic',
            name='secondary_keyword',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
